"""Add culture graph models

Revision ID: 051d4955fb26
Revises: 061cdb35003a
Create Date: 2025-12-01 22:18:32.755798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051d4955fb26'
down_revision = '061cdb35003a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('culture_element',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ethnic_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('culture_ethnic_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('culture_element_id', sa.Integer(), nullable=False),
    sa.Column('ethnic_group_id', sa.Integer(), nullable=False),
    sa.Column('culture', sa.Text(), nullable=False),
    sa.Column('customs', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['culture_element_id'], ['culture_element.id'], ),
    sa.ForeignKeyConstraint(['ethnic_group_id'], ['ethnic_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cultural_practice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('relation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['relation_id'], ['culture_ethnic_relation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cultural_practice')
    op.drop_table('culture_ethnic_relation')
    op.drop_table('ethnic_group')
    op.drop_table('culture_element')
    # ### end Alembic commands ###
