"""Add created_at field to user model

Revision ID: 061cdb35003a
Revises: c514b61ac649
Create Date: 2025-11-28 23:42:14.459739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061cdb35003a'
down_revision = 'c514b61ac649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ethnic_impression', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_ethnic_impression_user', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('ethnic_impression', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ethnic_impression_user', type_='foreignkey')

    # ### end Alembic commands ###
