"""Add VRScene model and enhance community models

Revision ID: 08f978b60b9e
Revises: 051d4955fb26
Create Date: 2025-12-02 22:17:42.389088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f978b60b9e'
down_revision = '051d4955fb26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if tables already exist before creating them
    # This is a workaround for SQLite's lack of transactional DDL
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    if 'tag' not in tables:
        op.create_table('tag',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
        )
    
    if 'vr_scene' not in tables:
        op.create_table('vr_scene',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('category', sa.String(length=50), nullable=False),
        sa.Column('image_url', sa.String(length=200), nullable=False),
        sa.Column('vr_url', sa.String(length=200), nullable=False),
        sa.Column('location', sa.String(length=100), nullable=True),
        sa.Column('ethnicity', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
        )
    
    if 'like' not in tables:
        op.create_table('like',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('post_id', sa.Integer(), nullable=True),
        sa.Column('story_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
        sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    
    if 'post_tags' not in tables:
        op.create_table('post_tags',
        sa.Column('post_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
        sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
        sa.PrimaryKeyConstraint('post_id', 'tag_id'),
        info={'bind_key': None}
        )
    # Handle column additions with existence checks
    with op.batch_alter_table('comment', schema=None) as batch_op:
        if 'story_id' not in [col['name'] for col in inspector.get_columns('comment')]:
            batch_op.add_column(sa.Column('story_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_comment_story_id', 'story', ['story_id'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        if 'category' not in [col['name'] for col in inspector.get_columns('post')]:
            batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        if 'likes' not in [col['name'] for col in inspector.get_columns('post')]:
            batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))
        if 'views' not in [col['name'] for col in inspector.get_columns('post')]:
            batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))

    with op.batch_alter_table('story', schema=None) as batch_op:
        if 'views' not in [col['name'] for col in inspector.get_columns('story')]:
            batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_column('views')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('views')
        batch_op.drop_column('likes')
        batch_op.drop_column('category')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('story_id')

    op.drop_table('post_tags')
    op.drop_table('like')
    op.drop_table('vr_scene')
    op.drop_table('tag')
    # ### end Alembic commands ###
