"""Add favorites table

Revision ID: 5656a7b5307c
Revises: b200ca23780a
Create Date: 2025-11-20 21:03:11.361870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5656a7b5307c'
down_revision = 'b200ca23780a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ethnic_impression_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ethnic_impression_id'], ['ethnic_impression.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'ethnic_impression_id')
    )
    with op.batch_alter_table('ethnic_impression', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_ethnic_impression_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ethnic_impression', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ethnic_impression_user_id', type_='foreignkey')

    op.drop_table('favorites')
    # ### end Alembic commands ###
