"""Add bio, ethnicity, school fields to user model

Revision ID: 68db113ac7ee
Revises: f3ca3a89f009
Create Date: 2025-12-17 22:35:55.824774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68db113ac7ee'
down_revision = 'f3ca3a89f009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pattern_recognition_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('input_image', sa.String(length=200), nullable=False),
    sa.Column('recognized_pattern', sa.String(length=120), nullable=False),
    sa.Column('recognition_score', sa.Float(), nullable=False),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('similarity_matrix', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pattern_id'], ['culture_pattern.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_table('sqlite_sequence') - 删除这一行，因为sqlite_sequence是SQLite系统表，不能删除
    with op.batch_alter_table('culture_pattern', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pattern_features', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('similarity_score', sa.Float(), nullable=True))

    with op.batch_alter_table('dance_competition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dance_competition_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dance_competition_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_dance_competition_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_dance_competition_status'), ['status'], unique=False)

    with op.batch_alter_table('dance_submission', schema=None) as batch_op:
        batch_op.create_index('idx_dance_score', ['dance_id', 'score'], unique=False)
        batch_op.create_index('idx_dance_status', ['dance_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_dance_submission_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dance_submission_dance_id'), ['dance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dance_submission_score'), ['score'], unique=False)
        batch_op.create_index(batch_op.f('ix_dance_submission_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_dance_submission_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint('uq_user_post_like', ['user_id', 'post_id'])
        batch_op.create_unique_constraint('uq_user_story_like', ['user_id', 'story_id'])

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_task_type'), ['task_type'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ethnicity', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('school', sa.String(length=100), nullable=True))

    with op.batch_alter_table('user_task', schema=None) as batch_op:
        batch_op.create_index('idx_user_task', ['user_id', 'task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_task_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_task_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_task_is_completed'), ['is_completed'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_task_is_completed'))
        batch_op.drop_index(batch_op.f('ix_user_task_created_at'))
        batch_op.drop_index(batch_op.f('ix_user_task_completed_at'))
        batch_op.drop_index('idx_user_task')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('school')
        batch_op.drop_column('ethnicity')
        batch_op.drop_column('bio')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_task_type'))
        batch_op.drop_index(batch_op.f('ix_task_deadline'))
        batch_op.drop_index(batch_op.f('ix_task_created_by'))
        batch_op.drop_index(batch_op.f('ix_task_created_at'))

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_story_like', type_='unique')
        batch_op.drop_constraint('uq_user_post_like', type_='unique')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('dance_submission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dance_submission_user_id'))
        batch_op.drop_index(batch_op.f('ix_dance_submission_status'))
        batch_op.drop_index(batch_op.f('ix_dance_submission_score'))
        batch_op.drop_index(batch_op.f('ix_dance_submission_dance_id'))
        batch_op.drop_index(batch_op.f('ix_dance_submission_created_at'))
        batch_op.drop_index('idx_dance_status')
        batch_op.drop_index('idx_dance_score')

    with op.batch_alter_table('dance_competition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dance_competition_status'))
        batch_op.drop_index(batch_op.f('ix_dance_competition_start_time'))
        batch_op.drop_index(batch_op.f('ix_dance_competition_end_time'))
        batch_op.drop_index(batch_op.f('ix_dance_competition_created_at'))

    with op.batch_alter_table('culture_pattern', schema=None) as batch_op:
        batch_op.drop_column('similarity_score')
        batch_op.drop_column('pattern_features')

    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_table('pattern_recognition_result')
    # ### end Alembic commands ###

