"""Add share count field and share table

Revision ID: 6f7828b50663
Revises: 70dc6c7eabf0
Create Date: 2025-12-03 22:20:31.728692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f7828b50663'
down_revision = '70dc6c7eabf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 检查share表是否存在，不存在才创建
    from sqlalchemy import inspect
    from sqlalchemy.exc import OperationalError
    
    inspector = inspect(op.get_bind())
    if 'share' not in inspector.get_table_names():
        op.create_table('share',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('submission_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('platform', sa.String(length=20), nullable=False),
        sa.Column('share_time', sa.DateTime(), nullable=True),
        sa.Column('ip_address', sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(['submission_id'], ['dance_submission.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    # 检查临时表是否存在，存在才删除
    if '_alembic_tmp_like' in inspector.get_table_names():
        op.drop_table('_alembic_tmp_like')
    # 检查share_count列是否存在，不存在才添加
    with op.batch_alter_table('dance_submission', schema=None) as batch_op:
        # 检查列是否存在
        dance_submission_columns = inspector.get_columns('dance_submission')
        share_count_exists = any(col['name'] == 'share_count' for col in dance_submission_columns)
        if not share_count_exists:
            batch_op.add_column(sa.Column('share_count', sa.Integer(), nullable=True))

    # 跳过like表的约束修改，因为数据库已经处于预期状态
    # with op.batch_alter_table('like', schema=None) as batch_op:
    #     batch_op.drop_constraint(batch_op.f('uq_user_like'), type_='unique')
    #     batch_op.create_unique_constraint('uq_user_post_like', ['user_id', 'post_id'])
    #     batch_op.create_unique_constraint('uq_user_story_like', ['user_id', 'story_id'])

    # 跳过user表的索引和约束修改，因为数据库已经处于预期状态
    # with op.batch_alter_table('user', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('uq_user_phone'))
    #     batch_op.create_unique_constraint('uq_user_phone', ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('uq_user_phone'), ['phone'], unique=1)

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_story_like', type_='unique')
        batch_op.drop_constraint('uq_user_post_like', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_like'), ['user_id', 'post_id', 'story_id'])

    with op.batch_alter_table('dance_submission', schema=None) as batch_op:
        batch_op.drop_column('share_count')

    op.create_table('_alembic_tmp_like',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=True),
    sa.Column('story_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name=op.f('uq_user_post_like')),
    sa.UniqueConstraint('user_id', 'story_id', name=op.f('uq_user_story_like'))
    )
    op.drop_table('share')
    # ### end Alembic commands ###
