"""Add dance competition models

Revision ID: 70dc6c7eabf0
Revises: 08f978b60b9e
Create Date: 2025-12-02 22:53:21.987170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70dc6c7eabf0'
down_revision = '08f978b60b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dance_competition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('video_url', sa.String(length=200), nullable=False),
    sa.Column('ethnicity', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['dance_competition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dance_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dance_id', sa.Integer(), nullable=True),
    sa.Column('video_url', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('score_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dance_id'], ['dance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_like'), type_='unique')
        batch_op.create_unique_constraint('uq_user_post_like', ['user_id', 'post_id'])
        batch_op.create_unique_constraint('uq_user_story_like', ['user_id', 'story_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('login_type', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('uq_user_phone', ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('login_type')
        batch_op.drop_column('phone')

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_story_like', type_='unique')
        batch_op.drop_constraint('uq_user_post_like', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_like'), ['user_id', 'post_id', 'story_id'])

    op.drop_table('dance_submission')
    op.drop_table('dance')
    op.drop_table('dance_competition')
    # ### end Alembic commands ###
