"""Add task submission model and extend task model

Revision ID: 96428af82050
Revises: 6f7828b50663
Create Date: 2025-12-16 00:24:47.189518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96428af82050'
down_revision = '6f7828b50663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip creating task_submission table if it already exists
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'task_submission' not in inspector.get_table_names():
        op.create_table('task_submission',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('task_id', sa.Integer(), nullable=False),
        sa.Column('file_url', sa.String(length=200), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('feedback', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    # Skip modifying like table to avoid conflicts with temporary tables
    # with op.batch_alter_table('like', schema=None) as batch_op:
    #     batch_op.alter_column('user_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    #     batch_op.create_unique_constraint('uq_user_post_like', ['user_id', 'post_id'])
    #     batch_op.create_unique_constraint('uq_user_story_like', ['user_id', 'story_id'])

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('file_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('file_types', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('file_size_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reward', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        # Check if task table has created_by column and foreign key constraint already exists
        conn = op.get_bind()
        inspector = sa.inspect(conn)
        task_columns = [col['name'] for col in inspector.get_columns('task')]
        if 'created_by' in task_columns:
            # Check if foreign key constraint already exists
            task_constraints = inspector.get_foreign_keys('task')
            has_created_by_fk = any(fk['constrained_columns'] == ['created_by'] for fk in task_constraints)
            if not has_created_by_fk:
                batch_op.create_foreign_key('fk_task_created_by', 'user', ['created_by'], ['id'])

    with op.batch_alter_table('user_task', schema=None) as batch_op:
        # Check if user_task table has submission_id column already
        conn = op.get_bind()
        inspector = sa.inspect(conn)
        user_task_columns = [col['name'] for col in inspector.get_columns('user_task')]
        if 'submission_id' not in user_task_columns:
            batch_op.add_column(sa.Column('submission_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_user_task_submission', 'task_submission', ['submission_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('submission_id')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('reward')
        batch_op.drop_column('deadline')
        batch_op.drop_column('file_size_limit')
        batch_op.drop_column('file_types')
        batch_op.drop_column('file_required')
        batch_op.drop_column('task_type')

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_story_like', type_='unique')
        batch_op.drop_constraint('uq_user_post_like', type_='unique')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('task_submission')
    # ### end Alembic commands ###
