"""add ethnic_elements to EthnicImpression

Revision ID: b200ca23780a
Revises: c97051bc922b
Create Date: 2025-11-20 20:30:40.939464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b200ca23780a'
down_revision = 'c97051bc922b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ethnic_impression', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ethnic_elements', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ethnic_impression', schema=None) as batch_op:
        batch_op.drop_column('ethnic_elements')

    # ### end Alembic commands ###
