"""Add story model

Revision ID: c9d3b971a808
Revises: 5656a7b5307c
Create Date: 2025-11-22 13:12:42.372623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d3b971a808'
down_revision = '5656a7b5307c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ethnicity', sa.String(length=50), nullable=False),
    sa.Column('school', sa.String(length=100), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # 移除对ethnic_impression表的修改，因为这可能已经存在

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 移除对ethnic_impression表的修改，因为这可能已经存在

    op.drop_table('story')
    # ### end Alembic commands ###
