"""Add detailed score fields to DanceSubmission

Revision ID: d208b0e1f45f
Revises: 96428af82050
Create Date: 2025-12-16 20:21:37.475334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd208b0e1f45f'
down_revision = '96428af82050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns exist before adding them to dance_submission table
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    dance_submission_columns = [col['name'] for col in inspector.get_columns('dance_submission')]
    
    with op.batch_alter_table('dance_submission', schema=None) as batch_op:
        if 'accuracy' not in dance_submission_columns:
            batch_op.add_column(sa.Column('accuracy', sa.Float(), nullable=True))
        if 'rhythm' not in dance_submission_columns:
            batch_op.add_column(sa.Column('rhythm', sa.Float(), nullable=True))
        if 'expression' not in dance_submission_columns:
            batch_op.add_column(sa.Column('expression', sa.Float(), nullable=True))
        if 'completeness' not in dance_submission_columns:
            batch_op.add_column(sa.Column('completeness', sa.Float(), nullable=True))

    # Skip modifying like table to avoid conflicts
    # with op.batch_alter_table('like', schema=None) as batch_op:
    #     batch_op.alter_column('user_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    #     batch_op.create_unique_constraint('uq_user_post_like', ['user_id', 'post_id'])
    #     batch_op.create_unique_constraint('uq_user_story_like', ['user_id', 'story_id'])

    # Skip creating foreign key on task table if it already exists
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    task_constraints = inspector.get_foreign_keys('task')
    has_created_by_fk = any(fk['constrained_columns'] == ['created_by'] for fk in task_constraints)
    if not has_created_by_fk:
        with op.batch_alter_table('task', schema=None) as batch_op:
            batch_op.create_foreign_key('fk_task_created_by', 'user', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip dropping foreign key on task table to avoid conflicts
    with op.batch_alter_table('task', schema=None) as batch_op:
        try:
            batch_op.drop_constraint(None, type_='foreignkey')
        except Exception:
            pass

    # Skip modifying like table to avoid conflicts
    # with op.batch_alter_table('like', schema=None) as batch_op:
    #     batch_op.drop_constraint('uq_user_story_like', type_='unique')
    #     batch_op.drop_constraint('uq_user_post_like', type_='unique')
    #     batch_op.alter_column('user_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)

    with op.batch_alter_table('dance_submission', schema=None) as batch_op:
        batch_op.drop_column('completeness')
        batch_op.drop_column('expression')
        batch_op.drop_column('rhythm')
        batch_op.drop_column('accuracy')

    # Skip creating system tables
    # op.create_table('sqlite_sequence',
    # sa.Column('name', sa.NullType(), nullable=True),
    # sa.Column('seq', sa.NullType(), nullable=True)
    # )
    # op.create_table('_alembic_tmp_like',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user_id', sa.INTEGER(), nullable=False),
    # sa.Column('post_id', sa.INTEGER(), nullable=True),
    # sa.Column('story_id', sa.INTEGER(), nullable=True),
    # sa.Column('created_at', sa.DATETIME(), nullable=True),
    # sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    # sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    # sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('user_id', 'post_id', name=op.f('uq_user_post_like')),
    # sa.UniqueConstraint('user_id', 'story_id', name=op.f('uq_user_story_like'))
    # )
    # ### end Alembic commands ###
