"""Add heritage models

Revision ID: f3ca3a89f009
Revises: d208b0e1f45f
Create Date: 2025-12-16 22:09:48.251139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3ca3a89f009'
down_revision = 'd208b0e1f45f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ancient_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('version_type', sa.String(length=50), nullable=False),
    sa.Column('publication_date', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.String(length=20), nullable=True),
    sa.Column('four_part_classification', sa.String(length=120), nullable=True),
    sa.Column('binding_form', sa.String(length=50), nullable=True),
    sa.Column('collection_unit', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('culture_pattern',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('era', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('carrier', sa.String(length=120), nullable=True),
    sa.Column('technique', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heritage_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_code', sa.String(length=20), nullable=False),
    sa.Column('project_name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('announcement_time', sa.String(length=50), nullable=False),
    sa.Column('declaration_region', sa.String(length=120), nullable=False),
    sa.Column('protection_unit', sa.String(length=120), nullable=False),
    sa.Column('inheritors', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_code')
    )
    op.create_table('tourism_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('star_level', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('dance_competition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dance_competition_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dance_competition_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_dance_competition_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_dance_competition_status'), ['status'], unique=False)

    with op.batch_alter_table('dance_submission', schema=None) as batch_op:
        batch_op.create_index('idx_dance_score', ['dance_id', 'score'], unique=False)
        batch_op.create_index('idx_dance_status', ['dance_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_dance_submission_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dance_submission_dance_id'), ['dance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dance_submission_score'), ['score'], unique=False)
        batch_op.create_index(batch_op.f('ix_dance_submission_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_dance_submission_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint('uq_user_post_like', ['user_id', 'post_id'])
        batch_op.create_unique_constraint('uq_user_story_like', ['user_id', 'story_id'])

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_task_type'), ['task_type'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ethnicity', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('school', sa.String(length=100), nullable=True))

    with op.batch_alter_table('user_task', schema=None) as batch_op:
        batch_op.create_index('idx_user_task', ['user_id', 'task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_task_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_task_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_task_is_completed'), ['is_completed'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_task_is_completed'))
        batch_op.drop_index(batch_op.f('ix_user_task_created_at'))
        batch_op.drop_index(batch_op.f('ix_user_task_completed_at'))
        batch_op.drop_index('idx_user_task')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('school')
        batch_op.drop_column('ethnicity')
        batch_op.drop_column('bio')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_task_type'))
        batch_op.drop_index(batch_op.f('ix_task_deadline'))
        batch_op.drop_index(batch_op.f('ix_task_created_by'))
        batch_op.drop_index(batch_op.f('ix_task_created_at'))

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_story_like', type_='unique')
        batch_op.drop_constraint('uq_user_post_like', type_='unique')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('dance_submission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dance_submission_user_id'))
        batch_op.drop_index(batch_op.f('ix_dance_submission_status'))
        batch_op.drop_index(batch_op.f('ix_dance_submission_score'))
        batch_op.drop_index(batch_op.f('ix_dance_submission_dance_id'))
        batch_op.drop_index(batch_op.f('ix_dance_submission_created_at'))
        batch_op.drop_index('idx_dance_status')
        batch_op.drop_index('idx_dance_score')

    with op.batch_alter_table('dance_competition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dance_competition_status'))
        batch_op.drop_index(batch_op.f('ix_dance_competition_start_time'))
        batch_op.drop_index(batch_op.f('ix_dance_competition_end_time'))
        batch_op.drop_index(batch_op.f('ix_dance_competition_created_at'))


    op.drop_table('tourism_resource')
    op.drop_table('heritage_project')
    op.drop_table('culture_pattern')
    op.drop_table('ancient_book')
    # ### end Alembic commands ###
